CREATE TABLE IF NOT EXISTS uuidIpMap (
  uuid TEXT PRIMARY KEY,
  IP TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS email (
  uuid TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  contents TEXT NOT NULL,
  IP TEXT NOT NULL
);

