// Generated by Wrangler on Mon Jul 01 2024 22:00:05 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  DB: D1Database;
  SEND_EMAIL_ADDRESS: string;
  MAIL_APP_PASS: string;
  RECEIVE_ADDRESS: string;
  WEB_FIREBASE_SERVICE_ACCOUNT: string;
  BREVO_API_KEY: string;
}
