#:schema node_modules/wrangler/config-schema.json
name = "remix-portfolio"
compatibility_date = "2024-06-20"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "remix-portfolio-db"
database_id = "0a5ac033-1df7-4da3-873d-2def2da6bd35"